#!/usr/bin/sh

# this configures the local machines according to the necessary values.

# In your terminal, type: 
#   $ `source local-setup`

# !! This file serves as a template and should therefore remain untouched. 
# Copy its content instead to, e.g. `my-local-setup` (in the same dir. )
# and customize the contents.
# `my-local-setup` is already added to .gitignore, and won't be synched upstream.

export PROJECT_ID=''
export GITHUB_USER=''
export GITHUB_EMAIL=''
export GITHUB_TOKEN=''
PROJECT_ROOT="${HOME}/add/path/to/repo"

gcloud config set project $PROJECT_ID


git config --global user.email $GITHUB_EMAIL
git config --global user.name $GITHUB_USER


GS_BUCKET="gs://${PROJECT_ID}-tfstate"

# create bucket to store infrastructure record: terraform state (tfstate)
gsutil mb $GS_BUCKET

# setup versioning to keep record of infrastractural changes 
if [[ $(gsutil versioning get $GS_BUCKET | awk '{print $2}') != 'Enabled' ]]; then
   gsutil versioning set on $GS_BUCKET
else
   echo "Versioning for ${GS_BUCKET} already enabled."
fi

# create service account credentials
gcloud iam service-accounts keys create ../.GSA_TERRAFORM_CLOUD.json --iam-account=terraform-cloud@ornate-reef-342810.iam.gserviceaccount.com

export GOOGLE_APPLICATION_CREDENTIALS="{$PROJECT_ROOT}/.GSA_TERRAFORM_CLOUD.JSON"
